#!/usr/bin/env python3
"""
Empirical Verification Test Suite for Milestone 4 InputLagSniper & Documentation
Generated by challenger_m4_2.
"""

import os
import sys
import re
import math
from pathlib import Path

DIST_DIR = Path("/Users/divyyadav/newws/monitor_test_hub/dist")
SRC_DIR = Path("/Users/divyyadav/newws/monitor_test_hub/src")
SNIPER_ASTRO = SRC_DIR / "components/diagnostics/InputLagSniper.astro"
ENGINE_TS = SRC_DIR / "engine/InputLagEngine.ts"
GLOBAL_CSS = SRC_DIR / "styles/global.css"

def get_relative_luminance(hex_color):
    """Calculate relative luminance according to WCAG 2.1 specification."""
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 3:
        hex_color = ''.join([c*2 for c in hex_color])
    r = int(hex_color[0:2], 16) / 255.0
    g = int(hex_color[2:4], 16) / 255.0
    b = int(hex_color[4:6], 16) / 255.0

    def adjust(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r_lin = adjust(r)
    g_lin = adjust(g)
    b_lin = adjust(b)

    return 0.2126 * r_lin + 0.7152 * g_lin + 0.0722 * b_lin

def contrast_ratio(hex1, hex2):
    """Calculate contrast ratio between two hex colors."""
    l1 = get_relative_luminance(hex1)
    l2 = get_relative_luminance(hex2)
    lighter = max(l1, l2)
    darker = min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)

def run_contrast_audit():
    print("\n--- 1. OPTICAL CONTRAST RATIO AUDIT (WCAG 2.1) ---")
    colors = {
        "Dark Canvas": "#08080a",
        "Dark Surface": "#0e0e11",
        "Dark Primary Text": "#ededed",
        "Dark Secondary Text": "#a1a1aa",
        "Dark Muted Text": "#71717a",
        "Dark Pass Signal": "#10b981",
        "Dark Warn Signal": "#f59e0b",
        "Dark Fail Signal": "#ef4444",
        "Dark Info Signal": "#06b6d4",
        
        "Light Canvas": "#f8fafc",
        "Light Surface": "#ffffff",
        "Light Primary Text": "#0f172a",
        "Light Secondary Text": "#475569",
        "Light Muted Text": "#64748b",
        "Light Pass Signal": "#059669",
        "Light Fail Signal": "#dc2626",
        "Light Info Signal": "#0891b2",
    }

    pairs_dark = [
        ("Dark Primary Text on Canvas", "#ededed", "#08080a", 4.5),
        ("Dark Secondary Text on Canvas", "#a1a1aa", "#08080a", 4.5),
        ("Dark Muted Text on Canvas", "#71717a", "#08080a", 3.0),
        ("Dark Pass Signal on Canvas", "#10b981", "#08080a", 3.0),
        ("Dark Fail Signal on Canvas", "#ef4444", "#08080a", 3.0),
        ("Dark Info Signal on Canvas", "#06b6d4", "#08080a", 3.0),
    ]

    pairs_light = [
        ("Light Primary Text on Canvas", "#0f172a", "#f8fafc", 4.5),
        ("Light Secondary Text on Canvas", "#475569", "#f8fafc", 4.5),
        ("Light Muted Text on Canvas", "#64748b", "#f8fafc", 3.0),
        ("Light Pass Signal on Canvas", "#059669", "#f8fafc", 3.0),
        ("Light Fail Signal on Canvas", "#dc2626", "#f8fafc", 3.0),
        ("Light Info Signal on Canvas", "#0891b2", "#f8fafc", 3.0),
    ]

    all_passed = True
    for name, fg, bg, req in pairs_dark + pairs_light:
        cr = contrast_ratio(fg, bg)
        passed = cr >= req
        if not passed:
            all_passed = False
        status = "PASS" if passed else "FAIL"
        print(f"[{status}] {name:<35}: {cr:.2f}:1 (Target >= {req}:1)")

    return all_passed

def run_cls_preallocation_audit():
    print("\n--- 2. CLS PRE-ALLOCATION & CONTAINER BOUNDS AUDIT ---")
    code = SNIPER_ASTRO.read_text(encoding="utf-8")

    checks = {
        "Main Viewport Container Height (h-80)": "h-80" in code,
        "Telemetry Box Min Height (min-h-[90px])": "min-h-[90px]" in code,
        "Telemetry Numeric Tabular Font (tabular-nums)": "tabular-nums" in code,
        "Histogram Container Height (h-28)": "h-28" in code,
        "Histogram Empty Msg Absolute Position (absolute inset-0)": "absolute inset-0" in code,
        "Instruction Overlay Absolute Position (absolute inset-0)": "absolute inset-0" in code,
        "Warning Banner Fixed Flex Layout": "flex items-center justify-between" in code,
        "Quantization Badge Hidden Pre-alloc": "hidden text-[10px]" in code
    }

    all_passed = True
    for check_name, passed in checks.items():
        if not passed:
            all_passed = False
        status = "PASS" if passed else "FAIL"
        print(f"[{status}] {check_name}")

    return all_passed

def run_focus_ring_audit():
    print("\n--- 3. FOCUS RINGS & KEYBOARD ACCESSIBILITY AUDIT ---")
    code = SNIPER_ASTRO.read_text(encoding="utf-8")
    css = GLOBAL_CSS.read_text(encoding="utf-8")

    interactive_elements = [
        ("Refresh Rate Select Focus Ring", r'id="sniper-hz-select"[^>]*focus:ring-2'),
        ("Polling Rate Select Focus Ring", r'id="sniper-poll-select"[^>]*focus:ring-2'),
        ("Mode Toggle Button Focus Ring", r'class:list=\{[^}]*focus:ring-2'),
        ("Viewport Container Tabindex", r'id="sniper-viewport-container"[^>]*tabindex="0"'),
        ("Viewport Container ARIA Role", r'id="sniper-viewport-container"[^>]*role="button"'),
        ("Viewport Container Focus Ring", r'id="sniper-viewport-container"[^>]*focus:ring-2'),
    ]

    all_passed = True
    for name, pattern in interactive_elements:
        found = bool(re.search(pattern, code))
        if not found:
            all_passed = False
        status = "PASS" if found else "FAIL"
        print(f"[{status}] {name}")

    # Check universal focus-visible in global.css
    has_universal_focus = "*:focus-visible" in css and "outline: 2px solid" in css
    status = "PASS" if has_universal_focus else "FAIL"
    print(f"[{status}] Universal focus-visible in global.css (*:focus-visible)")
    if not has_universal_focus:
        all_passed = False

    return all_passed

def run_html_build_audit():
    print("\n--- 4. STATIC HTML BUILD OUTPUT AUDIT ---")
    target_html = DIST_DIR / "input-lag-test/index.html"
    if not target_html.exists():
        print(f"[FAIL] HTML build output does not exist at {target_html}")
        return False

    content = target_html.read_text(encoding="utf-8")
    checks = {
        "InputLagSniper Rendered in HTML": "High-Refresh Input Lag & Reflex Reaction Sniper" in content,
        "Refresh Rate Select Rendered": 'id="sniper-hz-select"' in content,
        "Polling Rate Select Rendered": 'id="sniper-poll-select"' in content,
        "Viewport Container Rendered": 'id="sniper-viewport-container"' in content,
        "Sniper Canvas Rendered": 'id="sniper-canvas"' in content,
        "Telemetry Containers Rendered": 'id="telemetry-last"' in content and 'id="telemetry-avg"' in content,
        "Histogram Container Rendered": 'id="sniper-histogram-container"' in content,
    }

    all_passed = True
    for check_name, passed in checks.items():
        if not passed:
            all_passed = False
        status = "PASS" if passed else "FAIL"
        print(f"[{status}] {check_name}")

    return all_passed

def main():
    print("=" * 80)
    print("EMPIRICAL VERIFICATION HARNESS — CHALLENGER M4_2")
    print("=" * 80)

    c_pass = run_contrast_audit()
    cls_pass = run_cls_preallocation_audit()
    f_pass = run_focus_ring_audit()
    h_pass = run_html_build_audit()

    print("=" * 80)
    total_pass = c_pass and cls_pass and f_pass and h_pass
    print(f"OVERALL EMPIRICAL SUITE VERDICT: {'PASS' if total_pass else 'FAIL'}")
    print("=" * 80)
    sys.exit(0 if total_pass else 1)

if __name__ == "__main__":
    main()
